name: FinSecure Security Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.11"

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep SAST
        run: semgrep scan --config p/default .
              - name: Start OWASP Juice Shop
        run: |
          docker run -d --name juice-shop -p 3000:3000 bkimminich/juice-shop
          
          echo "Waiting for Juice Shop to start..."
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:3000/ > /dev/null; then
              echo "Juice Shop is ready."
              break
            fi
            sleep 2
          done

      - name: Run OWASP ZAP Baseline Scan
        continue-on-error: true
        run: |
          docker run --network host \
            -v "${{ github.workspace }}:/zap/wrk/:rw" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://127.0.0.1:3000 \
            -r zap-report.html

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap-report.html
